airflow:
  enabled: true
  airflow:
    image:
      repository: cschreep/airflow
      tag: "2.0.1"
      pullPolicy: Always
    executor: KubernetesExecutor
    config:
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "TRUE"
      AIRFLOW__CORE__LOAD_EXAMPLES: "FALSE"
    extraEnv:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_GRAPH
          value: test
        - name: REDIS_HOST
          value: helx-search-redis-master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-search-redis-secret
              key: password
        - name: ROGER_DATA_DIR
          value: "/opt/airflow/share/data"
        - name: DUG_LOG_LEVEL
          value: DEBUG
        - name: ELASTIC_API_HOST
          value: helx-search-elasticsearch-master
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-search-elastic-secret
              key: password
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              name: helx-search-elastic-secret
              key: username
        - name: NBOOST_API_HOST
          value: nboost $ TODO compute this
        - name: TRANQL_API_HOST
          value: helx-search-tranql-service
        - name: TRANQL_API_PORT
          value: "8081"
    extraVolumeMounts:
      - name: airflow-data
        mountPath: /opt/airflow/share/data
    extraVolumes:
      - name: airflow-data
        persistentVolumeClaim:
          claimName: helx-search-data

  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/helxplatform/roger.git"
      repoSubPath: "dags"
      branch: "feature/cicd-improvements"
      revision: "HEAD"
      syncWait: 60

  logs:
    path: /opt/airflow/share/logs
    persistence:
      enabled: true
      storageClass: "" ## WARNING: your StorageClass MUST SUPPORT `ReadWriteMany`
      accessMode: ReadWriteMany
      size: 1Gi

  redis:
    enabled: false

  externalRedis:
    host: helx-search-redis-master
    passwordSecret: helx-search-redis-secret
    passwordSecretKey: password
  flower:
    enabled: false
  workers:
    enabled: false

api:
  enabled: true
  web:
    deployment:
      extraEnv:
        - name: ELASTIC_API_HOST
          value: helx-search-elasticsearch-master
        - name: ELASTIC_API_PORT
          value: "9200"
        - name: ELASTIC_USERNAME
          valueFrom:
            secretKeyRef:
              name: helx-search-elastic-secret
              key: username
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-search-elastic-secret
              key: password
        - name: REDIS_HOST
          value: helx-search-redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helx-search-redis-secret
              key: password
        - name: NBOOST_API_HOST
          value: ""
  redis:
    enabled: false
  elasticsearch:
    enabled: false

elasticsearch:
  enabled: true
  imageTag: "7.12.0"
  clusterName: helx-search-elasticsearch
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helx-search-elastic-secret
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: helx-search-elastic-secret
          key: username

nboost:
  enabled: false

persistence:
  pvcSize: 1Gi

redis:
  enabled: true
  usePassword: true
  existingSecret: helx-search-redis-secret
  existingSecretPasswordKey: password
  image:
    repository: redislabs/redisgraph
    tag: 2.2.14
  redis:
    command: "redis-server"
  cluster:
    slaveCount: 1
  master:
    resources:
      requests:
        memory: 16Gi
        cpu: 200m
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379
  slave:
    resources:
      requests:
        memory: 2Gi
        cpu: 200m
    command: ""
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    extraFlags:
      - "--loadmodule /usr/lib/redis/modules/redisgraph.so"
    service:
      port: 6379

secrets:
  elastic:
    name: helx-search-elastic-secret
    elastic_user: elastic
  redis:
    name: helx-search-redis-secret

tranql:
  enabled: true
  annotations: {}
  redis:
    existingSecret: helx-search-redis-secret

ui:
  enabled: true
  extraEnv:
    - name: PUBLIC_URL
      value: ""