apiVersion: v1
kind: Service
metadata:
  {{- if .Values.web.service.annotations }}
  annotations: {{ toYaml .Values.web.service.annotations }}
  {{- end }}
  labels:
    app: {{ .Values.web.appName }}
    {{- include "api.labels" . | nindent 4 }}
  name: {{ .Values.web.service.name }}
  name: {{ include "api.web.fullname" . }}
spec:
  ports:
    - name: helx-search-api-port
      protocol: TCP
      port: {{ .Values.web.service.apiPort }}
      targetPort: {{ .Values.web.deployment.apiPort }}
  selector:
    app: {{ .Values.web.appName }}
  type: {{ .Values.web.service.type }}